imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

services:
  jobeet.backend.admin.job:
    class: Jobeet\BackendBundle\Admin\JobAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: jobeet, label: job }
    arguments: [ null, Jobeet\FrontendBundle\Entity\Job, JobeetBackendBundle:JobAdmin ]
  jobeet.backend.admin.category:
    class: Jobeet\BackendBundle\Admin\CategoryAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: jobeet, label: category }
    arguments: [ null, Jobeet\FrontendBundle\Entity\Category, JobeetBackendBundle:CategoryAdmin ]
  jobeet.backend.admin.affiliate:
    class: Jobeet\BackendBundle\Admin\AffiliateAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: jobeet, label: affiliate }
    arguments: [ null, Jobeet\FrontendBundle\Entity\Affiliate, JobeetBackendBundle:AffiliateAdmin ]
  lucene:
    class: Jobeet\FrontendBundle\Lucene\MyLucene
    arguments: [%kernel.root_dir%/cache/%kernel.environment%/lucene/index]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

parameters:
  max_jobs: 10
  max_jobs_category: 20

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Jobeet\BackendBundle\Entity\User