<?php

namespace Jobeet\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AffiliateobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRepository extends EntityRepository
{
	public function generateToken($from)
	{
		$token = sha1($from.rand(1111,9999));
		$existing_tokens = $this->getTokens();
		while (in_array($token, $existing_tokens))
		{
			$token = sha1($token);
		}
		return $token;
	}
	
	protected function getTokens()
	{
		$tokens = $this->createQueryBuilder('a')->select('a.token')->getQuery()->getResult();
		$tokens_array = array();
		foreach ($tokens as $t)
		{
			$tokens_array[] = $t['token'];
		}
		return $tokens_array;
	}
}